language: node_js
node_js:
  - '0.10'
branches:
  only:
    - master
before_install:
  - npm install -g grunt-cli bower
before_script:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - git config --global user.email "i@2fd.me"
  - git config --global user.name "Fede Ramirez"
  - bower install
script:
  - grunt travis
after_success:
  - echo -e "Done with magic\n"
env:
  global:
    secure: USNBfNsfQFF6UgNzXRXA+8mWc66WvOUXjIH5PRjbBRUfUFZkt0a74P7uW/IMJZ0XlQwbWCphzv6Rh1qfI5bbmh6nwlJtBgP6KCc/GrPyN61YrudmPZfiNrHFkylhELz82CE6oWZjZGRwlCsLa3IADo27azmQx7kJhko5t3war5A=
notifications:
  email:
    recipients:
      - i@2fd.me
